# @package action
_target_: posedreamer.filtering.actions.CopyFilesAction
dest_base_dir: ???  # e.g. action.dest_base_dir=/path/to/filtered-output
preserve_structure: false
copy_smpl: true
rename_files: false
